apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flex-arkitektur
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses}}
    - {{this}}
  {{/each}}
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 8080
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /.next/cache
  gcp:
    bigQueryDatasets:
      - name: flex_arkitektur_dataset
        permission: READWRITE
