export const naisAppTestdata = [
    {
        name: 'sykepengesoknad-backend',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '[]',
        inbound_apps: [
            'prod-gcp.flex.ditt-sykefravaer',
            'prod-gcp.flex.sykepengesoknad',
            'prod-gcp.flex.sykepengesoknad-arkivering-oppgave',
            'prod-gcp.flex.flex-internal-frontend',
            'prod-gcp.teamsykefravr.syfomodiaperson',
            'prod-gcp.tbd.sparkel-dokumenter',
        ],
        outbound_apps: [
            'prod-gcp.flex.sykepengesoknad-backend-redis',
            'prod-gcp.flex.sykepengesoknad-kvitteringer',
            'prod-gcp.flex.flex-syketilfelle',
            'prod-gcp.yrkesskade.yrkesskade-saker',
            'prod-gcp.teamsykefravr.istilgangskontroll',
            'prod-gcp.medlemskap.medlemskap-sykepenger-listener',
            'prod-gcp.team-soknad.innsending-api',
        ],
        outbound_hosts: [
            'pdl-api.prod-fss-pub.nais.io',
            'ereg-services.prod-fss-pub.nais.io',
            'team-inntekt-proxy.prod-fss-pub.nais.io',
            'flex-unleash-api.nav.cloud.nais.io',
        ],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.flex.sykepengesoknad',
            'nav-prod.flex.sykepengesoknad-aktivering',
            'nav-prod.flex.sykmeldinger-sendt-retry',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
            'nav-prod.pdl.leesah-v1',
            'nav-prod.pdl.leesah-v1-kor2024',
            'nav-prod.teamsykmelding.manuell-behandling-sykmelding',
            'nav-prod.teamsykmelding.ok-sykmelding',
            'nav-prod.teamsykmelding.syfo-bekreftet-sykmelding',
            'nav-prod.teamsykmelding.syfo-narmesteleder-leesah',
            'nav-prod.teamsykmelding.syfo-sendt-sykmelding',
        ],
        write_topics: [
            'nav-prod.flex.omrade-helse-etterlevelse',
            'nav-prod.flex.sykepengesoknad',
            'nav-prod.flex.sykepengesoknad-aktivering',
            'nav-prod.flex.sykmeldinger-sendt-retry',
        ],
    },
    {
        name: 'sykepengesoknad',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '["https://www.nav.no/syk/sykepengesoknad"]',
        inbound_apps: [],
        outbound_apps: [
            'prod-gcp.flex.sykepengesoknad-backend',
            'prod-gcp.flex.sykepengesoknad-kvitteringer',
            'prod-gcp.flex.flexjar-backend',
            'prod-gcp.okonomi.sokos-kontoregister-person',
            'prod-gcp.teamsykmelding.sykmeldinger-backend',
            'prod-gcp.personbruker.nav-dekoratoren',
        ],
        outbound_hosts: ['flex-unleash-api.nav.cloud.nais.io'],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
        ],
        write_topics: [],
    },
    {
        name: 'flexjar-backend',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '[]',
        inbound_apps: [
            'prod-gcp.flex.sykepengesoknad',
            'prod-gcp.flex.flexjar-frontend',
            'prod-gcp.flex.spinnsyn-frontend',
            'prod-gcp.flex.ditt-sykefravaer',
            'prod-gcp.teamsykmelding.dinesykmeldte',
            'prod-gcp.teamsykmelding.sykmeldinger',
            'prod-gcp.helsearbeidsgiver.spinntektsmelding-frontend',
            'prod-gcp.tbd.flexjar-proxy',
            'prod-gcp.teamsykefravr.syfomodiaperson',
            'prod-gcp.teamsykefravr.syfooversikt',
        ],
        outbound_apps: [],
        outbound_hosts: [],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
        ],
        write_topics: [],
    },
    {
        name: 'flexjar-frontend',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '["https://flexjar.intern.nav.no"]',
        inbound_apps: [],
        outbound_apps: ['prod-gcp.flex.flexjar-backend'],
        outbound_hosts: ['slack.com', 'api.slack.com', 'api.trello.com', 'trello.com'],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
        ],
        write_topics: [],
    },
    {
        name: 'flex-syketilfelle',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '[]',
        inbound_apps: [
            'prod-gcp.flex.sykepengesoknad-backend',
            'prod-gcp.teamsykmelding.sykmeldinger',
            'prod-gcp.teamsykmelding.sparenaproxy',
            'prod-gcp.teamsykmelding.syfosmregler',
            'prod-gcp.teamsykmelding.syfosmpapirregler',
            'prod-gcp.teamsykmelding.dinesykmeldte-kafka',
            'prod-gcp.teamsykmelding.syfosminfotrygd',
        ],
        outbound_apps: [],
        outbound_hosts: ['pdl-api.prod-fss-pub.nais.io'],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.flex.sykepengesoknad',
            'nav-prod.flex.syketilfellebiter',
            'nav-prod.helsearbeidsgiver.privat-sykepenger-inntektsmelding',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
            'nav-prod.teamsykmelding.syfo-bekreftet-sykmelding',
            'nav-prod.teamsykmelding.syfo-mottatt-sykmelding',
            'nav-prod.teamsykmelding.syfo-sendt-sykmelding',
        ],
        write_topics: ['nav-prod.flex.omrade-helse-etterlevelse', 'nav-prod.flex.syketilfellebiter'],
    },
    {
        name: 'spinnsyn-backend',
        cluster: 'prod-gcp',
        namespace: 'flex',
        ingresses: '[]',
        inbound_apps: [
            'prod-gcp.flex.spinnsyn-frontend-arkivering',
            'prod-gcp.flex.spinnsyn-frontend-interne',
            'prod-gcp.flex.spinnsyn-frontend',
            'prod-gcp.flex.ditt-sykefravaer',
        ],
        outbound_apps: ['prod-gcp.teamsykefravr.istilgangskontroll'],
        outbound_hosts: ['pdl-api.prod-fss-pub.nais.io'],
        read_topics: [
            'nav-prod.aura.kafka-canary-prod-gcp',
            'nav-prod.flex.sykepengesoknad',
            'nav-prod.nais-verification.kafka-canary-prod',
            'nav-prod.nais-verification.kafka-canary-prod-fss',
            'nav-prod.nais-verification.kafka-canary-prod-gcp',
            'nav-prod.tbd.utbetaling',
            'nav-prod.tbd.vedtak',
        ],
        write_topics: ['nav-prod.flex.vedtak-status'],
    },
]
